name: interactive
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pandas=1.5.3
  - plotly=5.12
  - dash=2.7.1
  - ipywidgets>=7.5
  - gunicorn=20.1
  - pip:
    - dash-bootstrap-components<1
